POST http://localhost:7777/auth/login
Content-Type: application/json

{
  "username": "abel",
  "password": "abel"
}

###
POST http://localhost:7777/auth/signup
Content-Type: application/json

{
  "username": "abel",
  "password": "abel"
}

###
DELETE http://localhost:7777/room/delete/all

###
DELETE http://localhost:7777/user/delete/all

###
POST http://localhost:7777/user/abel
Content-Type: application/json

{
  "username": "abel",
  "email": "abel@something.com",
  "password": "password",
  "rank": "3D"
}

###
GET http://localhost:7777/user/abel

